version: '3.5'

services:
  internetbanking.api01: &api
    image: ${DOCKER_REGISTRY-}internetbankingapi
    container_name: "intenetbanking.api01"
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    build:
      context: .
      dockerfile: InternetBanking.API/Dockerfile
    ports:
     - "8081:8080"     
    depends_on:
      - internetbanking.database
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
  internetbanking.api02:
    <<: *api
    container_name: "intenetbanking.api02"
    hostname: api02
    environment:
        - DB_HOSTNAME=db
    ports:
        - "8082:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - internetbanking.api01
      - internetbanking.api02
    ports:        
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
 
  internetbanking.database:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    # volumes:
    #   - ./.containers/internetbanking-db:/var/lib/postgresql/data
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    healthcheck:
      test: "exit 0"
      interval: "2s"
      timeout: "5s"
      retries: 5
    deploy:
      resources:
        limits:          
          cpus: "0.13"
          memory: "140MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1        